project:
  type: website

website:
  title: "Small Thoughts"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/spm1001
      - icon: linkedin
        href: https://www.linkedin.com/in/sameermodha/
      - icon: rss
        href: blog.xml
  google-analytics: G-HKL2T85FW9
  cookie-consent: true
format:
  html:
    theme: cosmo
    css: styles.css
    code-overflow: wrap
    code-tools:
      source: true
      toggle: true
      caption: Quarto Source

execute:
  freeze: auto
