project:
  type: website

website:
  title: "Small Thoughts"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/spm1001
      - icon: linkedin
        href: https://www.linkedin.com/in/sameermodha/
format:
  html:
    theme: cosmo
    css: styles.css
    code-overflow: wrap
    code-tools:
      source: true
      toggle: true
      caption: none

execute:
  freeze: auto
