baseURL = 'https://spm1001.planetmodha.com'
languageCode = 'en-gb'
title = 'spm1001'
theme = 'hugo-theme-stack' #'reveal-hugo'
timeout = '60s'
defaultContentLanguage = 'en'
copyright = 'Sameer Modha'


[pagination]
pagerSize = 50


[params]
    rssFullContent = false
    favicon = "/favicon.ico"

    # Nested tables for article, colorScheme, footer, and sidebar
    [params.article]
        math = true

    [params.colorScheme]
        toggle = false
        default = "light"

    [params.footer]
        since = 2015
        customText = "These opinions may have been mine, but certainly don't represent those of any past, present or indeed future employer"

    [params.sidebar]
        subtitle = "This is a subtitle" # Your subtitle is here


[menu]
    # Define your main menu if you have one, e.g.:
    # [[main]]
    #   identifier = "home"
    #   name = "Home"
    #   url = "/"
    #   weight = 10

    # Social links - each [[social]] creates a new item in the social menu

    [[menu.social]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://linkedin.com/in/sameermodha" # CHANGE THIS TO YOUR ACTUAL LINKEDIN PROFILE URL
        weight = 10
        [menu.social.params]
            icon = "brand-linkedin" # This icon refers to the Feather Icons or Font Awesome icons bundled/supported by the theme


    [[menu.social]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/spm1001"
        weight = 20 # Optional: Controls order, lower number appears first
        [menu.social.params]
            icon = "brand-github" # This icon refers to the Feather Icons or Font Awesome icons bundled/supported by the theme


    [[menu.social]]
        identifier = "bitly"
        name = "Bit.ly"
        url = "https://bit.ly/m/sameermodha"
        weight = 30 # Optional: Controls order, lower number appears first
        [menu.social.params]
            icon = "brand-bitly" # This icon refers to the Feather Icons or Font Awesome icons bundled/supported by the theme


[markup.goldmark.renderer]
    unsafe = true

[outputFormats.Reveal]
    baseName = "index"
    mediaType = "text/html"
    isHTML = true