baseURL = 'https://spm1001.planetmodha.com'
languageCode = 'en-gb'
title = 'spm1001'
theme = 'hugo-theme-stack' #'reveal-hugo'
timeout = "60s"
defaultContentLanguage = "en"

[pagination]
pagerSize = 50

[params]
    rssFullContent = false
    favicon = "/favicon.ico"

[menu]
    [[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/CaiJimmy/hugo-theme-stack"
    [[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/CaiJimmy/hugo-theme-stack"

    [social.params]
    icon = "brand-github"

    [[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com"

    [social.params]
    icon = "brand-twitter"

[params.article]
    math = true

[params.colorScheme]
toggle = false
default = "light"

[params.footer]
since = 2015
customText = "These opinions may have been mine, but certainly don't represent those of any past, present or indeed future employer"

[markup.goldmark.renderer]
    unsafe = true

[outputFormats.Reveal]
    baseName = "index"
    mediaType = "text/html"
    isHTML = true

